CREATE DATABASE BIBLIOTECA;
USE BIBLIOTECA;
CREATE TABLE AUTORES(
AUTOR_ID INT NOT NULL,
NOMBRE VARCHAR(100) NOT NULL
);
CREATE TABLE EDITORIALES (
EDITORIAL_ID INT NOT NULL,
NOMBRE VARCHAR(100) NOT NULL
);
CREATE TABLE LIBROS(
LIBROS_ID INT NOT NULL,
TITULO VARCHAR(255),
AUTOR_ID INT NOT NULL,
EDITORIAL_ID INT NOT NULL
);
CREATE TABLE MIEMBROS(
MIEMBRO_ID INT,
NOMBRE VARCHAR (50) NOT NULL,
APELLIDO VARCHAR(50) NOT NULL,
DIRECCION VARCHAR(200) NOT NULL,
TELEFONO VARCHAR(15) NOT NULL,
EMAIL VARCHAR(100) UNIQUE
);
CREATE TABLE TRANSACCIONES_LIBROS(
TRANSACCION_ID INT NOT NULL,
FECHA DATE NOT NULL,
TIPO VARCHAR(10),
LIBRO_ID INT NOT NULL,
MIEMBRO_ID INT NOT NULL
);


