USE BIBLIOTECA;

ALTER TABLE AUTORES ADD CONSTRAINT AUTOR_PK PRIMARY KEY(AUTOR_ID);

ALTER TABLE EDITORIALES ADD CONSTRAINT EDITORIAL_PK PRIMARY KEY(EDITORIAL_ID);

ALTER TABLE LIBROS ADD CONSTRAINT LIBROS_PK PRIMARY KEY(LIBROS_ID);

ALTER TABLE MIEMBROS ADD CONSTRAINT MIEMBRO_PK PRIMARY KEY(MIEMBRO_ID);

ALTER TABLE TRANSACCIONES_LIBROS ADD CONSTRAINT TRANSACCION_PK PRIMARY KEY(TRANSACCION_ID);

ALTER TABLE LIBROS ADD CONSTRAINT LIBRO_AUTOR_FK FOREIGN KEY (AUTOR_ID) 
REFERENCES AUTORES(AUTOR_ID);

ALTER TABLE LIBROS ADD CONSTRAINT LIBRO_EDITORIAL_FK FOREIGN KEY (EDITORIAL_ID)
REFERENCES EDITORIALES(EDITORIAL_ID);

ALTER TABLE TRANSACCIONES_LIBROS ADD CONSTRAINT TRANSACCION_LIBRO
FOREIGN KEY(LIBROS_ID) REFERENCES LIBROS(LIBROS_ID);

ALTER TABLE TRANSACCIONES_LIBROS ADD CONSTRAINT TRANSACCION_MIEMBRO FOREIGN KEY(MIEMBRO_ID)
REFERENCES MIEMBROS(MIEMBRO_ID)



