CREATE TABLE IF NOT EXISTS categorias (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT NOT NULL
);

INSERT INTO categorias (id, nombre) VALUES
(1, 'Entradas'),
(2, 'Platos Fuertes'),
(3, 'Postres'),
(4, 'Bebidas Frías'),
(5, 'Bebidas Calientes'),
(6, 'Ensaladas'),
(7, 'Sopas'),
(8, 'Mariscos'),
(9, 'Pizzas'),
(10, 'Especialidades')
ON CONFLICT (id) DO NOTHING;
