CREATE TABLE reservaciones (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  mesa_id BIGINT REFERENCES mesas(id) ON DELETE CASCADE,
  nombre_cliente VARCHAR(100) NOT NULL,
  fecha_hora TIMESTAMPTZ NOT NULL,
  personas INT NOT NULL CHECK (personas > 0),
  estado VARCHAR(20) DEFAULT 'confirmada' CHECK (estado IN ('confirmada', 'cancelada', 'completada'))
);
