CREATE TABLE mesas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  numero INT NOT NULL UNIQUE,
  capacidad INT NOT NULL,
  estado VARCHAR(20) DEFAULT 'disponible' CHECK (estado IN ('disponible', 'ocupada', 'reservada'))
);