CREATE TABLE empleados (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR(100) NOT NULL,
  puesto VARCHAR(50) NOT NULL, -- ej. Mesero, Cocinero, Cajero
  telefono VARCHAR(20),
  creado_en TIMESTAMPTZ DEFAULT NOW()
);