CREATE TABLE menu (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  categoria_id BIGINT REFERENCES categorias(id) ON DELETE SET NULL,
  nombre VARCHAR(100) NOT NULL,
  descripcion TEXT,
  precio NUMERIC(10, 2) NOT NULL CHECK (precio >= 0),
  disponible BOOLEAN DEFAULT true
);