CREATE TABLE pedidos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  mesa_id BIGINT REFERENCES mesas(id) ON DELETE SET NULL,
  empleado_id BIGINT REFERENCES empleados(id) ON DELETE SET NULL,
  -- Estados indicados en tu apunte:
  estado VARCHAR(20) DEFAULT 'pendiente' CHECK (estado IN ('pendiente', 'en preparacion', 'entregado')),
  total NUMERIC(10, 2) DEFAULT 0.00,
  creado_en TIMESTAMPTZ DEFAULT NOW()
);